apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-03
  labels:
    app: demo-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-03
  template:
    metadata:
      labels:
        app: demo-03
    spec:
      containers:
      - name: demo-03
        image: my-own-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: demo-03
  labels:
    app: demo-03
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    app: demo-03
  type: NodePort