apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-limit-pending-example
  labels:
    app: demo-deployment-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-limit-pending-example
  template:
    metadata:
      labels:
        app: deployment-limit-pending-example
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
        livenessProbe:
          tcpSocket:
            port: 80
        resources:
          requests:
            memory: "50G"
            cpu: "250m"
          limits:
            memory: "50G"
            cpu: "500m"
