apiVersion: v1
kind: PersistentVolume
metadata:
  name:  wp-pv
spec:
  capacity:
    storage: 100Mi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  volumeMode: Filesystem
  hostPath:
    # Windows: /run/desktop/mnt/host/c/users/chm/<pfad>
    # Mac/ Linux: /<pfad>
    path: <hier muss ein Pfad rein>
  claimRef:
    namespace: default
    name: wp-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi